Formik for QuestionsForm.js has been created
Build-Week-Mentor-Me-2019/front-end pull request #13
Opened 2019-11-22 02:51 UTC by whitneyxlachelle

2019-11-22 16:20 UTC, Jason-Aviles approved these changes

2019-11-22 19:04 UTC, hutchcrowley approved these changes
Can you add your node_modules folder and package files to your gitignore and submit a new pull request? We're having a merge conflict.

2019-11-22 19:08 UTC, hutchcrowley requested changes
Please see merge conflict. I think you might need to add your package files to your gitignore file. Ask Jason for more info.

2019-11-23 00:34 UTC, hutchcrowley requested changes

2019-11-23 00:34 UTC, hutchcrowley commented on src/styles/answersStyles.js
> +export const AnswerContainer = styled.div`
I styled our Answer, AnswerList, and some styles on QuestionList. Check them out and let me know if you want to keep mine, incorporate yours, or what. Thanks! Not sure why this wouldn't just let me merge everything anyway.

2019-11-23 00:34 UTC, hutchcrowley commented on src/components/Answers/AnswerForm.js
> +                <textarea name="answer" rows="4" cols="50" placeholder="Answer" value={newAnswer.answer} onChange={handleChange}  />
Hey I completely re-did AnswerForm to use Formik. check it out and let me know if you want to keep these changes or no.

2019-11-23 00:34 UTC, hutchcrowley commented on src/components/Answers/Answer.js
> +import { AnswerContainer } from '../../styles/answersStyles';
Please check my updated styles for the Answer component and if you want to keep these changes, we can. Not sure why it didn't just let me pull this in..

2019-11-25 02:57 UTC, whitneyxlachelle reviewed
I resolved the merging conflicts.

2019-11-25 03:31 UTC, merged